### ISSUE TITLE
Misleading description on pub.dev

### ISSUE THREAD

**Issue by realrk95** [jeroen1602/flutter_web_bluetooth#14]
Please change the description on pub.dev for this package. Windows, Linux, MacOS, iOS and Android don't work. This is misleading for people looking for a genuine cross platform solution.

**Comment by jeroen1602** [comment]
The supported platforms list on pub.dev is generated on their end.

It's true that this package only supports web. But it will nicely compile in your project if you target both native code and web code. It just won't work.

Also the package is called flutter_web_bluetooth. And the description says "Flutter web bluetooth is a Flutter plugin to add support for the web bluetooth api."

It's the same with this package for Bluez the linux Bluetooth library.

https://pub.dev/packages/bluez

**Comment by realrk95** [comment]
Thanks for the update. Is there a way for you to merge this into flutter_reactive_ble? It already supports android and ios, hence giving support for all platforms (Android, iOS from their package, and Mac, Windows and Linux through web). That will be the true cross platform solution.

**Comment by jeroen1602** [comment]
I'm not sure if it would work since Bluetooth web requires a pair flow. Where the user allowed access to a device and scanning for all devices in the area is not allowed.

But if the developers of `flutter_reactive_ble` want to add this library as a dependency to implement web support they are free to do do do.

**Comment by rohitsangwan01** [comment]
Hey @jeroen1602  @realrk95 , i was trying to merge this package with flutter_reactive_ble , you guys can contribute here ,  we can atleast merge main features like scanning , connecting and subscribing to characterstics , 
checkout my fork here,
https://github.com/rohitsangwan01/flutter_reactive_ble/tree/master/packages/reactive_ble_web
