### ISSUE TITLE
Can't find any service

### ISSUE THREAD

**Issue by lyricdon** [jeroen1602/flutter_web_bluetooth#23]
### This is my code 
```
 bool sup = FlutterWebBluetooth.instance.isBluetoothApiSupported;
    print('isBluetoothApiSupported  ' + sup.toString());
    FlutterWebBluetooth.instance.isAvailable.listen((event) {
      print('isAvailable  ' + event.toString());
    });

    final requestOptions = RequestOptionsBuilder.acceptAllDevices(optionalServices: BluetoothDefaultServiceUUIDS.VALUES.map((e) => e.uuid).toList());

    try {
      final BluetoothDevice device = await FlutterWebBluetooth.instance.requestDevice(requestOptions);

      print(device);
      device.connected.listen((event) {
        print('connected  ' + event.toString());
      });
      await device.connect();
      print('connect');

      sers = await device.discoverServices();
      print('sers  ' + sers.toString());
      device.services.listen((event) {
        setState(() {
          sers2 = event;
          print('services.listen  ' + sers.toString());
        });
      });
    } on UserCancelledDialogError {
      print(1);
    } on DeviceNotFoundError {
      print(2);
    }
  }
```
I run on MacOS with Android Studio, This is the console: 

isBluetoothApiSupported  true
isAvailable  true
isAvailable  true
Instance of 'BluetoothDevice'
connected  true
connect
connected  true
sers  []

I can connect, but I can't get any services
How to resolve?

**Comment by jeroen1602** [comment]
Could you check three things for me?

1. Check to see if there are any error messages in the webbrowser's console
2. Check if you can find services using the [example code](https://jeroen1602.github.io/flutter_web_bluetooth/#/)
3. Can you download a ble scanner app on your phone and check the services that it can discover?

**Comment by lyricdon** [comment]
1. No error console, just like this  : 
    isBluetoothApiSupported  true             js_primitives.dart:30 
2.  I had try with example code, I can connect, but It shows "No services found!" too, 
3.  I run app which uses `[flutter_blue_plus](https://pub.flutter-io.cn/packages/flutter_blue_plus)` package on my iPhone, connect to the same device and found service I want, like:  000000ff-0000-1000-8000-00805f9b34fb

**Comment by jeroen1602** [comment]
The UUID that you shared is not a default UUID so it is not in the list of default UUIDs. 

You will need to add it to the list of optional services when you create the request options or else you won't be able.to communicate with it.

**Comment by jeroen1602** [comment]
The service UUID that you send isn't a default service. Donut isn't in the default services list.

You will have to add it yourself to the optional services when you creat the  request options, else you won't be able to find it
________________________________

**Comment by lyricdon** [comment]
final requestOptions = RequestOptionsBuilder.acceptAllDevices(optionalServices: [
      '000000ff-0000-1000-8000-00805f9b34fb',
      '0000fff0-0000-1000-8000-00805f9b34fb'
    ]);

I've try like this , but seem like no change
I still can connect it, but no services found
