### ISSUE TITLE
MTU

### ISSUE THREAD

**Issue by lyricdon** [jeroen1602/flutter_web_bluetooth#24]
can u support MTU size api?

**Comment by jeroen1602** [comment]
Looking at the Bluetooth web specification there seems no way to change or even request the MTU size. So if I read it correctly there is no way currently to support this.

https://webbluetoothcg.github.io/web-bluetooth/#ref-for-exchange-mtu

**Comment by lyricdon** [comment]
Thanks for your reply!
Er..I have a problem,  when using the web bluetooth,  some data can write success, but some can not with the same character,  seem like my device ignore that. The api told me write success, but device doesn't work
And I tried write the same data by my phone to the device, and It works
Did the web bluetooth have some unknown limit when write data to character?

The data success: 
[2, 2, 242, 1, 0, 40, 55, 69, 68, 70, 53, 54, 67, 68, 65, 57, 57, 68, 69, 52, 49, 48, 55, 65, 52, 51, 51, 57, 67, 48, 53, 67, 69, 68, 65, 55, 55, 49, 52, 68, 70, 54, 55, 53, 51, 66, 48, 3]
The data failed:
[83, 75, 67, 70, 71, 123, 34, 109, 97, 99, 34, 58, 34, 54, 54, 55, 48, 67, 69, 66, 65, 34, 44, 34, 103, 114, 111, 117, 112, 34, 58, 56, 48, 48, 49, 44, 34, 114, 101, 115, 116, 97, 114, 116, 34, 58, 49, 125]

**Comment by lyricdon** [comment]
my code:
[flutter_web_ble](https://github.com/lyricdon/flutter_web_ble.git)

**Comment by lyricdon** [comment]
Hi, do u have any suggestion?

**Comment by jeroen1602** [comment]
It's difficult to see what your error is precisely, I did see this in the specification:

> If bytes is more than 512 bytes long (the maximum length of an attribute value, per [Long Attribute Values](https://webbluetoothcg.github.io/web-bluetooth/#long-attribute-values)) return a promise rejected with an [InvalidModificationError](https://webidl.spec.whatwg.org/#invalidmodificationerror) and abort these steps.

But your data doesn't seem to be longer than that limit.

What I can suggest you try is using `writeValueWithoutResponse` and seeing if that fixes it.

I'm also not sure if this [line](https://github.com/lyricdon/flutter_web_ble/blob/af96337b272bd338a0d19c802f5b6d41a0d2a9e9/lib/home_page.dart#L53) properly waits for the device to be connected, so you may just be sending data too early.

**Comment by lyricdon** [comment]
I tried, don't work,  the result is still one success, the other fail with nothing happened
Thanks a lot.
