### ISSUE TITLE
Can We Get Manufacturer Data or FilterOption by Manufacturer data

### ISSUE THREAD

**Issue by rohitsangwan01** [jeroen1602/flutter_web_bluetooth#25]
As title Says , can we get Manufacturer data of Scanned Devices , i know name and id is available Api , so it will be tricky to add manufacturer data in BluetoothDevice 
but At least we have filter by Manufacturer data option in requestDevice, can you implement that in this plugin

**Comment by jeroen1602** [comment]
This plugin is meant as a translation layer from Dart to the Web Bluetooth API. And that API has no way of filtering on the manufacturer in the `requestOptions` so I have no way of implementing it.

You could read the Manufacturer characteristic as soon as the user selects a new device and then show an error message that the device is not supported.
Though this won't stop the user from being able to pair an incorrect device.

**Comment by fotiDim** [comment]
@jeroen1602 according to https://googlechrome.github.io/samples/web-bluetooth/manufacturer-data-filter.html and https://stackoverflow.com/questions/67020600/web-bluetooth-want-to-filter-on-manufacturer-data-when-using-navigator-bluetoot there should be support for Manufacturer Data Filter in Web Bluetooth. Am I misreading it?

**Comment by jeroen1602** [comment]
You are right, I went from memory and originally implemented it based on the [mdn](https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth/requestDevice) docs.

I'll add the [manufacturerData](https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothlescanfilterinit-manufacturerdata) and [serviceData](https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothlescanfilterinit-servicedata) to the filters.

**Comment by jeroen1602** [comment]
A new version should be live soon with the new filters

**Comment by rohitsangwan01** [comment]
> A new version should be live soon with the new filters
Great , Thank You
