### ISSUE TITLE
How to determine the current connected device ?

### ISSUE THREAD

**Issue by ihorkozar** [jeroen1602/flutter_web_bluetooth#26]
@jeroen1602 How can I determine the device with which the interaction is currently taking place. My program works with the same type of devices with different IDs. I need to show the user the number of the device with which he is now interacting.
The code below permanently prints all devices that were connected during the current browser session.
At the same time, the browser works with the last one connected, how to determine the last one?

```
FlutterWebBluetooth.instance.devices.listen((devices) {
      for (var device in devices) {
        print(device.name);
        device.connected.listen((connected) {
          if (connected) {
            print('Connected ${device.name}');
          }
        });
      }
```

**Comment by jeroen1602** [comment]
If I understand your issue correctly then you want to know know the new device that the user has connected to.

This is indeed difficult to do when listening to the `devices` stream. But the `FlutterWebBluetooth.instance.requestDevice(requestOptions)` method already returns the new device (or at least a future that resolves into the new device). Can't you just use that?
