### ISSUE TITLE
Signal strength 

### ISSUE THREAD

**Issue by tmtong** [jeroen1602/flutter_web_bluetooth#28]
Thanks for your great work
Is it possible to get the signal strength of a device without pairing it ?

**Comment by jeroen1602** [comment]
There is a whole advertisement segment of the API I haven't implemented yet or played around with. So I'm not 100% sure, but I believe you have to pair a device first before being able to find it.

And the found devices get lost the next time the users refreshes the browser. However if you enable the `enable-experimental-web-platform-features` flag in chrome (or chrome like browsers) it will remember the list of devices between sessions.

**Comment by tmtong** [comment]
If I use flutter_blue package

When I scan for devizes

**Comment by jeroen1602** [comment]
Thanks for the example code. It seems that it is possible with the Bluetooth Web API. However it has not been implemented in the library yet.

I'll try and get it working, but I can't promise it will be very soon since I only have some weekends to work on it.
