### ISSUE TITLE
Getting meta dependency issue

### ISSUE THREAD

**Issue by rohitsangwan01** [jeroen1602/flutter_web_bluetooth#30]
flutter_web_bluetooth ^0.0.8 requires meta >=1.3.0 <1.8.0. And because every version of flutter_localizations from sdk depends on meta 1.8.0

Because every version of flutter_test from sdk depends on meta 1.8.0 and flutter_web_bluetooth  depends on meta >=1.3.0 <1.8.0, flutter_test from sdk is incompatible with flutter_web_bluetooth

**Comment by jeroen1602** [comment]
Version 0.0.9 should be live now on [pub.dev](https://pub.dev/packages/flutter_web_bluetooth)
