### ISSUE TITLE
Doesn't work with the iOS Bluefy browser

### ISSUE THREAD

**Issue by jeroen1602** [jeroen1602/flutter_web_bluetooth#5]
Characteristic discovery doesn't seem to work for the iOS browser. Not sure why yet.

Link to browser: https://apps.apple.com/us/app/bluefy-web-ble-browser/id1492822055

**Comment by ihorkozar** [comment]
As far as I understand the problem is actual and not solved (

**Comment by jeroen1602** [comment]
That is correct.

I don't have access to an iPhone or a Mac to debug this so it would be appreciated if someone could try and debug this

**Comment by rohitsangwan01** [comment]
@jeroen1602 am working with flutterWebBluetooth on Bluefy browser , and after little debugging , 
when we call , 
`service.getCharacteristic(characteristicId)` or getCharacteristics list method , we get this error
`Unsupported operation : JSObject does not have broadcast`

**Comment by jeroen1602** [comment]
Thanks for the help @rohitsangwan01 
That error is probably being thrown at this line https://github.com/jeroen1602/flutter_web_bluetooth/blob/89fa8fccb042209882b69f1eca3e95b1e48c8e2f/lib/web/web_bluetooth_characteristic_properties.dart#L229

The Bluefy browser probably doesn't have the Bluetooth API as far implemented as this library expects. Can you try and remove this check on a local copy and see if it works then? I have a feeling that maybe some other features are also not implemented and will need additional exceptions.

**Comment by jeroen1602** [comment]
@rohitsangwan01 are none of the properties supported or just very few of them?

Because if it is none then the whole properties object should be made optional in the service. Otherwise all the properties that it doesn't support should be made optional as well as some `hasPropertyX` methods added.

Could you create a list of the properties it does support?

**Comment by rohitsangwan01** [comment]
@jeroen1602 i tested all of them one by one , and none of them is working

**Comment by rohitsangwan01** [comment]
@jeroen1602 sounds good , maybe we can check  _JSUtil.hasProperty only when user tries to retrieves that property 
, then based on result either we can send null ( set all properties optional ) , or we can Through Error like you said

**Comment by rohitsangwan01** [comment]
A temporary fix for now
https://github.com/jeroen1602/flutter_web_bluetooth/pull/29

**Comment by jeroen1602** [comment]
I added a more permanent fix in #37.

So I believe it should not work for the Bluefy browser.

I also did some looking around and I believe the Bluefy browser is based on this Github project: https://github.com/daphtdazz/WebBLE this will be useful for future reference

**Comment by rohitsangwan01** [comment]
> I also did some looking around and I believe the Bluefy browser is based on this Github project: https://github.com/daphtdazz/WebBLE this will be useful for future reference

by using some references from WebBLE , i created something similar for flutter
https://pub.dev/packages/web_view_ble
so using my package , we can build a browser for IOS/android which can support ble
