### ISSUE TITLE
Support advertisement

### ISSUE THREAD

**Issue by josh-burton** [jeroen1602/flutter_web_bluetooth#6]
It looks like this plugin doesn't support advertisement. Is it possible?

**Comment by jeroen1602** [comment]
The web Bluetooth api does support advertisements, I just haven't implemented it yet.

You will however need to request a device from the user before you can watch for the advertisements, so I'm not sure how useful it will be. Also the paired devices are cleared each time the user refreshes the page, unless you enable the `Experimental Web Platform features` flag.
