### ISSUE TITLE
Unable to getting Services of Bluetooth Device

### ISSUE THREAD

**Issue by Abhishekvlog** [jeroen1602/flutter_web_bluetooth#63]
I have connected ble device using flutter_web_bluetooth library, now i trying to get ble device services but i'm getting empty list of services, here is my code, could you please tell me do i need to do some modification in this code for getting services.

 **connectedDevice?.discoverServices().then((services) async {
      services.forEach((service) {
        print("uuid - ${service.uuid}");
      });
    });**

and I tried this also.

 **List<BluetoothService>? services = await connectedDevice?.discoverServices();**

**Comment by jeroen1602** [comment]
When requesting a device you need to define what services you are going to communicate with. If you don't do this then no services will be available.

For example:

```dart
// Define the services you want to communicate with here!
final requestOptions = RequestOptionsBuilder.acceptAllDevices(optionalServices: [
  BluetoothDefaultServiceUUIDS.deviceInformation.uuid
]);

try {
  final device = await FlutterWebBluetooth.instance.requestDevice(requestOptions);
} on UserCancelledDialogError {
  // The user cancelled the dialog
} on DeviceNotFoundError {
  // There is no device in range for the options defined above
}
```

**Comment by Abhishekvlog** [comment]
yes, I defined already but not getting list of ble services,

**final requestOptions = RequestOptionsBuilder.acceptAllDevices(
        optionalServices: [
          BluetoothDefaultServiceUUIDS.deviceInformation.uuid,
          "my_service_uuid" // service uuid
        ]);
    try {
      connectedDevice = await FlutterWebBluetooth.instance.requestDevice(requestOptions);
      await connectedDevice?.connect();
      connected.value = true;
      connectedDevice?.discoverServices().then((services) async {
        print("service -- $services");
      });
    }
    on UserCancelledDialogError {
      // The user cancelled the dialog
    } on DeviceNotFoundError {
      // There is no device in range for the options defined above
    }**

**Comment by Abhishekvlog** [comment]
Thanks now I got BLE services, now i need to get real time data from bluetooth device, unable to enter in inner block

```
  late StreamSubscription<ByteData> notificationSubscription;

  Future<void> startNotification() async {
    if (desiredCharacteristic != null) {
      await desiredCharacteristic!.startNotifications();

    // unable to get inside this block
      notificationSubscription = desiredCharacteristic!.value.listen((value) {
        // Process the data received in 'value'
        Uint8List dataBytes = Uint8List.view(value.buffer);
        print('Notification received: $dataBytes');
      });
    }
  }

```

**Comment by jeroen1602** [comment]
Can you first check if the desired characteristic supports notifications?

You can do this using `characteristic.properties.notify`. If this is `false` then the characteristic doesn't support notifications.

You can work around this by periodically calling `characteristic.readValue`.

Another reason could be the implementation in the browser. I do remember that some promises in some browser just never resolve. For example the `FlutterWebBluetooth.instance.requestLEScan` doesn't ever return on Linux.
