### ISSUE TITLE
Manufacturer Data Map is empty in advertisements

### ISSUE THREAD

**Issue by rohitsangwan01** [jeroen1602/flutter_web_bluetooth#77]
Manufacturer Data map is empty in advertisements, probably because to discover manufacturer data in advertisements, we have to also pass `optionalManufacturerData` in request filters, as mentioned [here](https://github.com/WebBluetoothCG/web-bluetooth/issues/598#issuecomment-1302487513)

**Comment by jeroen1602** [comment]
I have added `optionalManufacturerData` to the request options as well as an enum with all the registered manufacture's identifiers. (not yet released though)

Does this solve your problem?

**Comment by rohitsangwan01** [comment]
@jeroen1602 thanks for the update, but am still not getting Manufacturer data in advertisements, not sure if am missing something,

am trying to pass manufacturer identifier for apple devices like this : 
       [ 0x004c], or also tried, 0x4C from BluetoothDefaultManufacturerIdentifiers
       
but still getting empty Maniufacturer data in device
<img width="376" alt="Screenshot 2024-02-02 at 10 26 17 AM" src="https://github.com/jeroen1602/flutter_web_bluetooth/assets/59526499/0d532810-565f-4040-a869-f87634764e10">

**Comment by rohitsangwan01** [comment]
Seems like manufacturer data related part is not stable yet, i tried this code in browser, and sometimes i got Manufacturer data, and sometimes not


```js

console.log("Requesting Bluetooth Device...");
navigator.bluetooth
  .requestDevice({
    acceptAllDevices: true,
    optionalManufacturerData: [0x12d, 0x4c],
  })
  .then((device) => {
    console.log("> Requested " + device.name);

    device.addEventListener("advertisement received", (event) => {
      console.log("Advertisement received.");
      console.log("  Device Name: " + event.device.name);
      console.log("  Device ID: " + event.device.id);
      console.log("  RSSI: " + event.rssi);

      event.manufacturerData.forEach((valueDataView, key) => {
        const hexString = [...new Uint8Array(valueDataView.buffer)]
          .map((b) => b.toString(16).padStart(2, "0"))
          .join(" ");
        console.log(
          `ManufacturerData Data: ` + key + "\n    (Hex) " + hexString
        );
      });
    });

    console.log('Watching advertisements from "' + device.name + '"...');
    return device.watchAdvertisements();
  })
  .catch((error) => {
    console.log("Ahh! " + error);
  });
```

**Comment by jeroen1602** [comment]
Are you trying to communicate with iBecaons? Because I noticed while testing that they are on the block list and will thus not show up/ work.

**Comment by rohitsangwan01** [comment]
@jeroen1602 am trying on Chrome ( MacOS )
And ble devices are my earBuds, Android phone in peripheral mode using NRFConnect or Iphone as Ble devices
Everything works fine, except the manufacturer data is empty 
Though its discovering fine in native plugins with these devices

**Comment by jeroen1602** [comment]
I think I have fixed the problem

The conversion from a JS map to a dart map was bugged so it didn't add adything resulting in empty manufacture data.

I have fixed this now and will release a new version shortly!
