### ISSUE TITLE
Couldn't find all of the services!

### ISSUE THREAD

**Issue by thefakhreddin** [jeroen1602/flutter_web_bluetooth#9]
I've successfully managed to connect to the ble device and get its services by both calling _discoverServices_ and _services_ on the BluetoothDevice object.
The problem is that it only returns 3 primary services namely 1800, 1801, and 180a which are not useful to me and are for generic access, generic attributes, and device information respectively.
I'm looking for FFF0 service which holds the characteristics FFF1 and FFF2 for reading and writing data.
*Note that I've already found and worked with the FFF0 service with both the **flutter_blue** package for android and ios and **NRF connect** mobile app; meaning that the service indeed exists.
As I decided to expand my project to the web, I thought that **flutter_web_bluetooth** is a suitable alternative.
In short:
A service is missing from the services list. Does anyone know how to solve this problem?

```
/// getting bluetooth devices
await FlutterWebBluetooth.instance.requestDevice(
        RequestOptionsBuilder.acceptAllDevices(
            optionalServices: BluetoothDefaultServiceUUIDS.VALUES
                .map((e) => e.uuid)
                .toList()));

FlutterWebBluetooth.instance.devices
        .firstWhere(
            (devices) => devices.any((device) => device.name == "NAME"))
        .then((devices) async {
      /// storing the device in a custom object member of type BluetoothDevice
      Bluetooth.connectedDevice =
          devices.firstWhere((device) => device.name == "NAME");
      Bluetooth.connectedDevice.connect();
      
      /// getting services after device is connected 
      StreamSubscription subscription;
      subscription = Bluetooth.connectedDevice.connected.listen((event) async {
        print("waiting for device to be connected");
        if (event) {
          Bluetooth.connectedDevice.discoverServices().then((services) async {
            services.forEach((service) {
              print(service.uuid);
            });
          });
          subscription.cancel();
        }
      });
    });
```

It returns three services with uuids:
00001800-0000-1000-8000-00805F9B34FB
00001801-0000-1000-8000-00805F9B34FB
0000180a-0000-1000-8000-00805F9B34FB

But I'm looking for:
0000FFF0-0000-1000-8000-00805F9B34FB

**Comment by jeroen1602** [comment]
The service you are looking for is not part of the `BluetoothDefaultServiceUUIDS` list and thus you will need to add it in the `acceptAllDevices` function as an optional service else the web browser won't show it to you even if it is there.

Also some services are part of a blacklist and are thus not able to be used, it should print int he console if this is the case.

**Comment by thefakhreddin** [comment]
@jeroen1602 
Thank you very much. Yes, That was certainly the solution. 
Does the same principle hold for the characteristics? Do I have to add the characteristics that I'm looking for in the service somewhere?
The charachtrestics that I'm loooking for are:
0000fff1-0000-1000-8000-00805f9b34fb for reading and
0000fff2-0000-1000-8000-00805f9b34fb for writing.

Here's the code:

```
StreamSubscription subscription;
      subscription = Bluetooth.connectedDevice.connected.listen((event) async {
        print("waiting for device to be connected");
        if (event) {
          try {
            Bluetooth.connectedDevice.discoverServices().then((services) async {
              Bluetooth.writeCharacteristic = await services
                  .firstWhere((service) => service.uuid == SERVICE_UUID)
                  .getCharacteristic(WRITE_UUID);
            });
            print("succ");
            Bluetooth.writeCharacteristic.writeValueWithoutResponse(
                Uint8List.fromList([0x01, 3, 0, 255]));
          } catch (e) {
            print("err");
          }
          subscription.cancel();
        }
      });
    });
```
My concole propmts "succ" and "err" right after that. Seemingly because it cannot `writeValueWithoutResponse` on the `Bluetooth.writeCharacteristic`

**Comment by thefakhreddin** [comment]
@jeroen1602 Perfect it worked! Thank you very much.
